spring:
  datasource:
    username: kanowory
    password: Tenczynek13!
    url: jdbc:sqlserver://morfeusz.wszib.edu.pl:1433;databaseName=kanowory;encrypt=false;
  jpa:
    hibernate:
      ddl-auto: update
